In [1]:
import numpy as np 

In [2]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [10]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(array2.shape) #this is kind of lenght of array

(15,)


In [11]:
a = array2.reshape(3,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [12]:
print("Shape: ",a.shape)

Shape:  (3, 5)


In [13]:
print("Dimension: ",a.ndim)

Dimension:  2


In [14]:
print("Data Type: ",a.dtype.name)

Data Type:  int32


In [16]:
print("Size: ",a.size)

Size:  15


In [17]:
print("Type: ",type(a))

Type:  <class 'numpy.ndarray'>


In [18]:
array3  = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
zeros[0,0] = 5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78021391e-306, 1.86921687e-306],
       [1.37959672e-306, 7.56599128e-307, 1.11256817e-306,
        1.06811422e-306, 1.42417221e-306],
       [1.11260619e-306, 8.90094053e-307, 1.86919378e-306,
        1.06809792e-306, 1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307, 8.90111707e-307]])

In [25]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
a = np.linspace(0,10,20)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [30]:
list = [1,2,3,4]
array = np.array([5,6,7,8])
print(list)
print(array)   #the difference of array and list

[1, 2, 3, 4]
[5 6 7 8]


In [34]:
a = np.array([1,2,3])
b = a 
c = a 
b[0] = 5
print(a,b,c) 
#why the code gives us this output? because we do the all spaces the same
#and if one space effected then all spaces effect like that 

[5 2 3] [5 2 3] [5 2 3]


In [40]:
a = np.array([1,2,3,4,5,6,7])
a[0:4]

array([1, 2, 3, 4])

In [41]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [43]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
b[:,1]

array([2, 7])

In [46]:
b[1,:]

array([ 6,  7,  8,  9, 10])

In [47]:
b[1,1:4]

array([7, 8, 9])

In [48]:
b[-1,:]

array([ 6,  7,  8,  9, 10])

In [49]:
b[:,-1]

array([ 5, 10])